#!/bin/sh

# This should fix applications that have problems with default execution, like
# apps that don't respect xrandr, apps that are Java, apps with lodpi, etc,
# running them through override_execution allows me to have fine control over
# how apps execute at the same time I get to keep the defaults for each
# application. This also does not mess with .desktop applications
override_execution() {
    read -r cmd
    case $cmd in
        "spotify") echo "$cmd --force-device-scale-factor=1.5" ;;
        "datagrip") echo "env _JAVA_AWT_WM_NONREPARENTING=1 $cmd" ;;
        "discord"|"discord-canary") echo "$cmd --no-sandbox" ;;
        *) echo "$cmd" ;;
    esac
}

dmenu_path | dmenu "$@" | override_execution | ${SHELL:-"/bin/sh"} &
